### ISSUE TITLE
TopoBlender-master\source\Surface_mesh.h:14: error: C2011: 'opengp::Surface_mesh': 'class' type redefinition

### ISSUE THREAD

**Issue by cravisjan97** [ialhashim/TopoBlender#3]
I tried building .pro file on QTCreator and I get many errors on source/Surface_mesh.h. I am using https://github.com/ialhashim/GeoTopo/blob/master/source/external/SurfaceMesh/surface_mesh/Surface_mesh.h from https://github.com/ialhashim/GeoTopo. I also get ```C:\Users\csundaram\Desktop\TopoBlender-master\TopoBlender-master\source\Surface_mesh.h:1773: error: C2027: use of undefined type 'opengp::Surface_mesh'``` error and syntax error for 'Vertex'. It would be really helpful if there is a fix to this?

**Comment by ialhashim** [comment]
Sounds like a compiler error. I am not sure what the issue is from your description.

**Comment by cravisjan97** [comment]
Thanks for the reply! I am building TopoBlender.pro on QTCreator software on Windows 10. I am using Qt 5.15 version. I have tried building with the following compilers: 

- MSVC 2019 - 64 bit
- UWP - 64 bit
- MSVC 2017 - 64 bit

I get the same error in compiling Surface_mesh.h in all these compilers. Can you shed some light on how you run the application?

**Comment by ialhashim** [comment]
Its been 4 years since I looked at this code so I am not very confident on what is the problem.

TopoBlender needs files from (https://github.com/ialhashim/GeoTopo). I think the code you are looking at references headers at (GeoTopo/tree/master/source/external/SurfaceMesh).

Try to look into that and figure out how to move forward.
